#! /usr/bin/env python3

import argparse
import sys
from graph import Graph
from generators import generate_hamiltonian, generate_non_hamiltonian

def print_help():
    print("Help \tShow this message")
    print("Print \tPrint the current state of the graph")
    print("Euler \tFind an Eulerian cycle in the graph")
    print("Hamilton \tFind a Hamiltonian cycle in the graph")
    print("Stats \tShow statistics about the graph")
    print("Exit \tExit the program")

def main():
    parser = argparse.ArgumentParser(description='Projekt 4 - Algorytmy z powracaniem')
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--hamilton', action='store_true', help='Znajdź cykl Hamiltona')
    group.add_argument("--non-hamilton", action='store_true', help='Znajdź cykl nie-Hamiltona')
    args = parser.parse_args()

    try: 
        current_graph = None

        if args.hamilton:
            nodes_input = input("nodes> ")
            saturations_input = input("saturations> ")
            current_graph = generate_hamiltonian(int(nodes_input), int(saturations_input))
        elif args.non_hamilton:
            nodes_input = input("nodes> ")
            current_graph = generate_non_hamiltonian(int(nodes_input))
        while True:
            action_input = input("action> ").strip().lower()
            if action_input == "help":
                print_help()
            if action_input == "print":
                if current_graph:
                    print(current_graph)
                else:
                    print("Brak grafu do wyświetlenia.")
            elif action_input == "euler":
                pass
            elif action_input == "hamilton":
                pass
            elif action_input == "stats":
                pass
            elif action_input == "exit":
                break
    except Exception as e:
        print(f"Błąd danych wejściowych: {e}", file=sys.stderr)
        sys.exit(1)
    except EOFError:
        pass
    except KeyboardInterrupt:
        print()

if __name__ == "__main__":
    main()